<?php 
$day = getdate();
$x = $day["mday"];

switch ($x) {
    case '1';
        $y = "Джонатан Свифт";
    break;
    case '2';
        $y = "Кристофер Райс";
    break;
    case '3';
        $y = "Дэвид Фегерти";
    break;
    case '4';
        $y = "Цицерон";
    break;
    case '5';
        $y = "Роберт Кийосаки";
    break;
    case '6';
        $y = "Бенджамин Франклин";
    break;
    case '7';
        $y = "Томас Эдисон";
    break;
    case '8';
        $y = "Джулия Кэмерон";
    break;
    case '9';
        $y = "Дэйв Рэмси";
    break;
    case '10';
        $y = "Иоганн Вольфганг фон Гёте";
    break;
    case '11';
        $y = "Джим Рон";
    break;
    case '12';
        $y = "Айн Рэнд";
    break;
    case '13';
        $y = "Дэйв Рэмси";
    break;
    case '14';
        $y = "Сенека";
    break;
    case '15';
        $y = "Элеонора Рузвельт";
    break;
    case '16';
        $y = "Франклин Рузвельт";
    break;
    case '17';
        $y = "Норман Пил";
    break;
    case '18';
        $y = "Джордж Хорас Лоример";
    break;
    case '19';
        $y = "Томас Джефферсон";
    break;
    case '20';
        $y = "Пол Гетти";
    break;
    case '21';
        $y = "Генри Форд";
    break;
    case '22';
        $y = "Бернард Шоу";
    break;
    case '23';
        $y = "Роберт Аллен";
    break;
    case '24';
        $y = "Малькольм Форбс";
    break;
    case '25';
        $y = "Стив Джобс";
    break;
    case '26';
        $y = "Неизвестный автор";
    break;
    case '27';
        $y = "Финеас Тейлор Барнум";
    break;
    case '28';
        $y = "Джек Бенни";
    break;
    case '29';
        $y = "Бенджамин Грэм";
    break;
    case '30';
        $y = "Роберт Кийосаки";
    break;
    case '31';
        $y = "Ким Гарст";
    break;
    }
?>